### ISSUE TITLE
[ENH] HTML Editor Designer/Source Modes

### ISSUE THREAD

**Issue by thabaum** [ADefWebserver/ADefWebserver.Module.HtmlTextV2#10]
Source Mode for the HTML EDITOR can be used instead of or along with the RAW HTML Editor.
`RadzenHtmlEditorSource - edit the HTML source as text.`
![image](https://github.com/ADefWebserver/ADefWebserver.Module.HtmlTextV2/assets/13577556/9bce0e7e-ce83-491d-ba9d-0de1226e1836)

I have successfully added most all logic needed with one exception of a hopefully minor bug retaining data switching from source back to design mode.
![image](https://github.com/ADefWebserver/ADefWebserver.Module.HtmlTextV2/assets/13577556/da201e55-5339-491c-8448-4d1f6f6673de)

**Comment by thabaum** [comment]
@ADefWebserver I will generate a pull request for this feature now and maybe figure out the issue with the retention of content switching from source to design mode in the html editor.  This is pretty much an overhaul of the HmtlEditor.Blazor project with a couple things added like a HtmlEditorTextArea component and this source mode enhancement.

This should be worked into things as we integrate and try to limit things hoping it works for most all solutions.

I think this will cover most of the updates needed for the HTML Editor to be fully functional utilizing the latest Radzen logic.  I will surf around for more fixes they have as needed to other files.

Merge in order to avoid conflicts in files.  I wont update files I updated in the other PR and don't need to as long as it gets merged first.

**Comment by ADefWebserver** [comment]
@thabaum - Ok I merged both PRs but now it won't build :( No stress, its just you and I, but, when you get a chance can you take a look at it? I may be offline until tomorrow.
